### ISSUE TITLE
Setup releases and putting in pypi

### ISSUE THREAD

**Issue by kelle** [astrodbtoolkit/astrodb_scripts#12]
Make this repo pip installable and have releases and version numbers.

**Comment by arjunsavel** [comment]
Looks like we can't make this repo explicitly pip installable right now. From what I'm seeing, PyPI doesn't allow direct dependencies (e.g., GitHub dependencies), so we can't include AstrodbKit2. See [here](https://stackoverflow.com/questions/68073819/pypi-install-requires-direct-links) and [here](https://github.com/python-poetry/poetry/issues/2828) for discussion. Thoughts?

**Comment by kelle** [comment]
need to run this in order to get latest version installed:
`pip install --force-reinstall git+https://github.com/astrodbtoolkit/astrodb_scripts.git@main`

**Comment by arjunsavel** [comment]
@dr-rodriguez I feel like I might've already asked this — but what are your thoughts on putting AstrodbKit2 on PyPI? That'd let us do the same for packages that depend on AstrodbKit2 like this scripts repo.

**Comment by kelle** [comment]
I thought astrodbkit2 was on pypi.  It's pip installable.

**Comment by dr-rodriguez** [comment]
That's right: https://pypi.org/project/astrodbkit2/ 
The only reason to use the git install is to capture changes that aren't in an official release

**Comment by arjunsavel** [comment]
Whoops! Somehow didn't catch that. Thanks!

**Comment by arjunsavel** [comment]
Scripts merged (#17). To-do: set up secrets, make first release (0.1).

**Comment by arjunsavel** [comment]
Done! Viewable [here](https://pypi.org/project/astrodb-scripts/) on PyPI.
