### ISSUE TITLE
Open readthedocs here?

### ISSUE THREAD

**Issue by arjunsavel** [astrodbtoolkit/astrodb_scripts#8]

**Comment by arjunsavel** [comment]
Sphinx_astropy? Take a look

**Comment by arjunsavel** [comment]
be sure to add logo!

**Comment by arjunsavel** [comment]
Looks like astropy isn't (anymore?) using a simple HTML theme: https://github.com/astropy/astropy/blob/main/docs/conf.py

**Comment by kelle** [comment]
Closed by #9
